apiVersion: 1

deleteDatasources:
- name: 'Prometheus'
- name: 'InfluxDB'

datasources:
- access: 'proxy'
  editable: true
  is_default: true
  name: 'Prometheus'
  uid: '6R74VAnVz'
  org_id: 1
  type: 'prometheus'
  url: 'http://prometheus:9090'
  version: 1
- access: 'proxy'
  editable: true
  is_default: false
  name: 'InfluxDB (op-geth)'
  uid: '4knV40nVb'
  org_id: 1
  type: 'influxdb'
  database: 'opgeth'
  url: 'http://influxdb:8086'
  version: 1
